export const WORKFLOW = [
"USES_SUPPLIER",
"FROM_SUPPLIER",
"GENERATES_PURCHASE_ORDER",
"FULFILLED_BY_SHIPMENT",
"INSPECTS_SHIPMENT"
];

export const SUPPORT = [
"OWNED_BY",
"PROCURES_MATERIAL",
"ORDERS_MATERIAL",
"PROVIDED_BY_SUPPLIER",
"ORDERED_FROM_SUPPLIER"
];

export const RESOURCE = [
"FOR_MATERIAL",
"STORED_IN",
"QUOTES_FOR_MATERIAL"
];

export const PRIORITY = {
    OWNED_BY: 1,
    USES_SUPPLIER: 2,
    FROM_SUPPLIER: 3,
    PROCURES_MATERIAL: 4,
    ORDERED_FROM_SUPPLIER: 5,
    ORDERS_MATERIAL: 6,
    PROVIDED_BY_SUPPLIER: 7,
    QUOTES_FOR_MATERIAL: 8,
    FOR_MATERIAL: 9,
    STORED_IN: 10
};